version: "3.7"
services:
  api_service:
    build: .
    ports:
      - 8080:8080
    environment:
      - server_port=8080
      - spring_datasource_username=user
      - spring_datasource_password=p@55w0rd
    depends_on:
      - maria_db
    command: sh -c './wait-for mysql_db:3306 -- npm start'
  maria_db:
    image: "mariadb"
    restart: always
    ports:
      - 3307:3306
    volumes:
      - './data:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: demo
      MYSQL_USER: user
      MYSQL_PASSWORD: p@55w0rd
      MYSQL_ROOT_PASSWORD: p@55w0rd
